# Generated by Django 5.0.6 on 2025-01-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideastar',
            name='user',
        ),
        migrations.AddField(
            model_name='ideastar',
            name='session_key',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
