# Generated by Django 5.0.6 on 2025-01-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_remove_ideastar_user_ideastar_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='dev_tool',
            field=models.CharField(blank=True, default='django', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='interest',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
