# Generated by Django 5.1.4 on 2025-01-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='actors',
            field=models.CharField(default='Unknown', max_length=300),
        ),
        migrations.AddField(
            model_name='review',
            name='director',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='running_time',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
